export type Seller = 'Kabum' | 'Terabyte' | 'Mercado Livre' | 'Pichau' | 'Amazon';

export type Category =
	| 'MLB-NOTEBOOKS'
	| 'MLB-SCHOOL_AND_OFFICE_PAPERS'
	| 'MLB-HEADPHONES'
	| 'MLB-LAPTOP_KEYBOARDS'
	| 'MLB-PROJECTORS'
	| 'MLB-HARD_DRIVES_AND_SSDS_ENCLOSURES'
	| 'MLB-AUDIO_AND_VIDEO_CABLES_AND_ADAPTERS'
	| 'MLB-TONERS'
	| 'MLB-NETWORK_CABLE_ADAPTERS'
	| 'MLB-MEMORY_READERS'
	| 'MLB-3D_PRINTER_FILAMENTS'
	| 'MLB-UPS_BATTERIES'
	| 'MLB-SCREEN_CLEANERS'
	| 'MLB-PRINTER_INKS'
	| 'MLB-COMPUTER_MICE'
	| 'MLB-MOUSE_PADS'
	| 'MLB-LAPTOP_CHARGERS'
	| 'MLB-NETWORK_CABLES'
	| 'MLB-ALL_IN_ONE_COMPUTERS'
	| 'MLB-KEYBOARD_AND_MOUSE_KITS'
	| 'MLB-ROUTERS_AND_WIRELESS_SYSTEMS'
	| 'MLB-COMPUTER_PROCESSORS'
	| 'MLB-COMPUTER_MOTHERBOARDS'
	| 'MLB-DESKTOP_COMPUTER_KITS'
	| 'MLB-GRAPHICS_CARDS'
	| 'MLB-RAM_MEMORY_MODULES'
	| 'MLB-DESKTOP_COMPUTER_COOLERS_AND_FANS'
	| 'MLB-FINGERPRINT_READERS'
	| 'MLB-COMPUTER_EQUIPMENT_AND_REPLACEMENTS'
	| 'MLB-NETWORK_CARDS'
	| 'MLB-HARD_DRIVES_AND_SSDS'
	| 'MLB-DATA_CABLES_AND_ADAPTERS'
	| 'MLB-LAPTOP_REPLACEMENT_INTERNAL_SPEAKERS'
	| 'MLB-LAPTOP_SCREENS'
	| 'MLB-PC_THERMAL_COMPOUND_PASTES'
	| 'MLB-MOLEX_CABLES'
	| 'MLB-DESKTOP_COMPUTER_POWER_SUPPLIES'
	| 'MLB-DESKTOP_COMPUTER_CASES'
	| 'MLB-CPU_HOLDERS'
	| 'MLB-COMPUTER_MONITORS'
	| 'MLB-MONITOR_POWER_SUPPLIES'
	| 'MLB-TV_AND_MONITOR_MOUNTS'
	| 'MLB-VIDEO_CAPTURE_DEVICES'
	| 'MLB-PENDRIVES'
	| 'MLB-HARD_DRIVES_AND_SSDS_CADDIES';

export interface Price {
	seller: Seller;
	amount: number;
	originalPrice?: number;
	discount?: number;
	promo?: string;
	endsAt?: Date;
}

export interface Product {
	id: string;
	title: string;
	thumbnail: string;
	category: Category;
	displayPrice: Price;
	prices: Price[];
}
